### ISSUE TITLE
Problem with SomaWorkflowEngine

### ISSUE THREAD

**Issue by BenoitDamota** [neurospin/pylearn-epac#40]
Hello,

When I run the main() in pylearn-mulm/mulm/models.py all the jobs failed with:

```
Traceback (most recent call last):
  File "./brainomics/pylearn-epac/bin/epac_mapper", line 78, in <module>
    f = open(relative_filepath, 'r')
IOError: [Errno 2] No such file or directory: './0.job'
```

Nothing was written in the working directory but in a temporary one like /tmp/tmpIklj65 
but the wrong path was passed to the epac_mapper.

**Comment by JinpengLI** [comment]
EPAC defines a "working directory" in /tmp/tmpIklj65 created by tempfile.mkdtemp(), and then soma-workflow works on this directory. On your computer, it seems that soma-workflow cannot define /tmp/tmpIklj65 as working directory. When using gabriel, EPAC map this working directory to grabriel.

Could you run unit test of epac and give me some feedbacks?  Just to check if EPAC works correctly or not on your computer.

```
$ python xxx/pylearn-epac/epac/tests/test_multi_processes.py
```

Many thanks for the feedback,
Jinpeng

**Comment by BenoitDamota** [comment]
Thank you for your help.

```
$ python ./brainomics/pylearn-epac/epac/tests/test_multi_processes.py 
light mode
E
======================================================================
ERROR: test_examples_local_engine (__main__.EpacWorkflowTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./brainomics/pylearn-epac/epac/tests/test_multi_processes.py", line 74, in test_examples_local_engine
    self._compare_two_node(wf, sfw_engine_wf)
  File "./brainomics/pylearn-epac/epac/tests/test_multi_processes.py", line 48, in _compare_two_node
    self._compare_leaf_res(leaf_res1, leaf_res2)
  File "./brainomics/pylearn-epac/epac/tests/test_multi_processes.py", line 54, in _compare_leaf_res
    == leaf_res2[i][leaf_res2[i].keys()[0]][key]))
AttributeError: 'NoneType' object has no attribute 'keys'

----------------------------------------------------------------------
Ran 1 test in 3.855s

FAILED (errors=1)
```

**Comment by JinpengLI** [comment]
According to the error, it seems that epac cannot write out job files in /tmp using tempfile.mkdtemp() or maybe it cannot change working directory to the created working directory. I just wrote a test script to test working directory of soma-workflow. Please first update local master branch of EPAC:

```
$ cd xxx/pylearn-epac/
```

and then run:

```
$ git pull
$ python ./epac/tests/test_swf_wd.py
```

And let me know if there is an error. And then, you can try again

```
$ cd xxx/pylearn-mulm
$ git pull
$ python ./mulm/models.py
```

If there is still errors, please goto tmp to find a directory like /tmp/tmp06uw4F

and run **$ tree** to let me know which files are in /tmp/tmp06uw4F.

```
$ cd /tmp/tmp06uw4F
$ tree
.
├── 0.job
├── 1.job
├── dataset
│   ├── dict_index.txt
│   ├── X.npy
│   └── Y.npy
└── epac_tree
    ├── ColumnSplitter
    │   ├── ColumnSplitter(nb=0)
    │   │   ├── store.pkl
    │   │   ├── store.pkl_01.npy
    │   │   └── store.pkl_02.npy
    │   ├── ColumnSplitter(nb=1)
    │   │   ├── store.pkl
    │   │   ├── store.pkl_01.npy
    │   │   └── store.pkl_02.npy
    │   ├── ColumnSplitter(nb=2)
    │   │   ├── store.pkl
    │   │   ├── store.pkl_01.npy
    │   │   └── store.pkl_02.npy
    │   └── ColumnSplitter(nb=3)
    │       ├── store.pkl
    │       ├── store.pkl_01.npy
    │       └── store.pkl_02.npy
    ├── execution_tree.pkl
    ├── execution_tree.pkl_01.npy
    ├── execution_tree.pkl_02.npy
    └── execution_tree.pkl_03.npy
```

Thanks,
Jinpeng

**Comment by BenoitDamota** [comment]
It works fine now. Thank you for your help.
